from typing import Type
from pydantic import BaseModel, Field
import json
import os
from langchain_core.tools import BaseTool
from langchain.agents import AgentExecutor, create_react_agent
from langchain_core.prompts import PromptTemplate
from langchain_openai import ChatOpenAI
from dotenv import load_dotenv

# Local modules
from utils import calculate_ascvd_10yr_risk
from rag import get_vector_store

load_dotenv()

# --- Schemas ---
class RiskAssessmentInput(BaseModel):
    patient_data: str = Field(description='A JSON string containing the keys: "age", "sex", "race", "total_cholesterol", "hdl_cholesterol", "systolic_bp", "smoker", "diabetes", "bp_meds"')

class GuidelineRAGInput(BaseModel):
    query: str = Field(description="Medical query to search within the guidelines.")

class RecommendationSynthesisInput(BaseModel):
    input_data: str = Field(description='A JSON string containing the keys: "risk_tier" and "retrieved_context"')

class SelfCritiqueInput(BaseModel):
    draft_recommendation: str = Field(description="The draft recommendation generated by the synthesis tool")

# --- Tools ---
class RiskAssessmentTool(BaseTool):
    name: str = "RiskAssessmentTool"
    description: str = 'Computes 10-year ASCVD risk via the 2013 ACC/AHA Pooled Cohort Equations. Input MUST be a valid JSON string with keys "age", "sex", "race" ("white" or "black"), "total_cholesterol", "hdl_cholesterol", "systolic_bp", "smoker", "diabetes", "bp_meds". Validated for ages 40-79.'
    args_schema: Type[BaseModel] = RiskAssessmentInput

    def _run(self, patient_data: str) -> str:
        try:
            data = json.loads(patient_data)
        except Exception:
            return "Error: Input MUST be a valid JSON string containing the patient vitals."

        age = int(data.get("age", 0))
        sex = str(data.get("sex", "male"))
        race = str(data.get("race", "white"))
        total_cholesterol = float(data.get("total_cholesterol", 0))
        hdl_cholesterol = float(data.get("hdl_cholesterol", 0))
        systolic_bp = float(data.get("systolic_bp", 0))
        smoker = bool(data.get("smoker", False))
        diabetes = bool(data.get("diabetes", False))
        bp_meds = bool(data.get("bp_meds", False))

        res = calculate_ascvd_10yr_risk(age, sex, total_cholesterol, hdl_cholesterol, systolic_bp, smoker, diabetes, bp_meds, race=race)
        return json.dumps(res)

class GuidelineRAGTool(BaseTool):
    name: str = "GuidelineRAGTool"
    description: str = "Retrieves semantic similarity search passages from the clinical guidelines database."
    args_schema: Type[BaseModel] = GuidelineRAGInput
    db: object = None

    def __init__(self, **data):
        super().__init__(**data)
        self.db = get_vector_store()

    def _run(self, query: str) -> str:
        docs = self.db.similarity_search(query, k=5)
        # Format citations
        formatted = ""
        for d in docs:
            source = d.metadata.get("source", "Unknown Document")
            page = d.metadata.get("page", 0)
            formatted += f"Source: {source} (Page {page})\\nContent: {d.page_content}\\n\\n"
        return formatted if formatted else "No relevant guidelines found."

class RecommendationSynthesisTool(BaseTool):
    name: str = "RecommendationSynthesisTool"
    description: str = 'Generates structured care plans spanning screening, lifestyle, pharmacological, and follow-up given context. Input MUST be a valid JSON string with keys "risk_tier" and "retrieved_context".'
    args_schema: Type[BaseModel] = RecommendationSynthesisInput

    def _run(self, input_data: str) -> str:
        try:
            data = json.loads(input_data)
            risk_tier = data.get("risk_tier", "Unknown")
            retrieved_context = data.get("retrieved_context", "")
        except Exception:
            return 'Error: Input MUST be a valid JSON string with keys "risk_tier" and "retrieved_context".'
            
        prompt = f"""
        You are a clinical recommendation synthesizer.
        Patient Risk Tier: {risk_tier}
        Retrieved Medical Guidelines:
        {retrieved_context}
        
        Generate a structured care plan containing:
        1. Screening Schedule
        2. Lifestyle Interventions
        3. Pharmacological Considerations
        4. Follow-up Actions
        
        Use the exact guidelines cited above to ground your answers.
        """
        chat = ChatOpenAI(
            model=os.environ.get("HF_CHAT_MODEL"),
            base_url=os.environ.get("HF_CHAT_URL"),
            api_key=os.environ.get("HUGGINGFACEHUB_API_TOKEN")
        )
        response = chat.invoke(prompt)
        return response.content

class SelfCritiqueTool(BaseTool):
    name: str = "SelfCritiqueTool"
    description: str = "Applies a Reflexion self-evaluation loop to validate completeness of generated recommendations."
    args_schema: Type[BaseModel] = SelfCritiqueInput

    def _run(self, draft_recommendation: str) -> str:
        rubric = """
        Evaluate if the recommendation contains:
        1. All 4 output fields (Screening, Lifestyle, Pharmacological, Follow-up).
        2. At least one guideline citation.
        3. Personalized to the patient risk tier.
        4. No contraindicated suggestions.
        """
        
        prompt = f"""
        Examine the following draft recommendation against the completeness rubric:
        {rubric}
        
        Draft:
        {draft_recommendation}
        
        If it meets all criteria, output 'PASS: ' followed by the recommendation.
        If it is missing anything, concisely describe what is missing and provide an 'IMPROVED: ' version.
        """
        chat = ChatOpenAI(
            model=os.environ.get("HF_CHAT_MODEL"),
            base_url=os.environ.get("HF_CHAT_URL"),
            api_key=os.environ.get("HUGGINGFACEHUB_API_TOKEN")
        )
        response = chat.invoke(prompt)
        return response.content

# --- Agent Construction ---
def create_agent():
    llm = ChatOpenAI(
        model=os.environ.get("HF_CHAT_MODEL"),
        base_url=os.environ.get("HF_CHAT_URL"),
        api_key=os.environ.get("HUGGINGFACEHUB_API_TOKEN")
    )
    
    tools = [
        RiskAssessmentTool(),
        GuidelineRAGTool(),
        RecommendationSynthesisTool(),
        SelfCritiqueTool()
    ]
    
    prompt = PromptTemplate.from_template(
        """You are an autonomous Preventive Care Recommendation Agent.
Answer the following questions as best you can. You have access to the following tools:

{tools}

To use a tool, please use the following format:

```
Thought: Do I need to use a tool? Yes
Action: the action to take, should be one of [{tool_names}]
Action Input: the input to the action
Observation: the result of the action
```

When you have a final answer to provide to the user, or if you do not need to use a tool, you MUST use the format:

```
Thought: Do I need to use a tool? No
Final Answer: [your response here]
```

Begin!

Question: {input}
Thought:{agent_scratchpad}"""
    )
    
    agent = create_react_agent(llm, tools, prompt)
    agent_executor = AgentExecutor(
    agent=agent,
    tools=tools,
    verbose=True,
    max_iterations=6,
    early_stopping_method="generate",
    handle_parsing_errors=True
)
    return agent_executor
