import streamlit as st

from agent import create_agent
from schemas import PatientProfile

st.set_page_config(page_title="Preventive Care Recommendation Agent", layout="wide")

st.title("Cardiovascular Preventive Care Agent")
st.markdown("""
This application uses an Agentic AI-powered framework leveraging LangChain, LangGraph, and
a RAG knowledge base of clinical guidelines to generate personalized preventive care recommendations.
""")

st.warning(
    "**Educational demo — not a validated clinical tool.** Risk is estimated with the published "
    "2013 ACC/AHA Pooled Cohort Equations, but the recommendation text is generated by an LLM and "
    "has not been reviewed by a clinician. Do not use this to make real medical decisions; talk to "
    "a healthcare provider instead.",
    icon="⚠️",
)


@st.cache_resource
def load_agent():
    return create_agent()


graph = load_agent()

RISK_TIER_COLOR = {
    "Low": "green",
    "Borderline": "orange",
    "Intermediate": "orange",
    "High": "red",
}

with st.sidebar:
    st.header("Patient Data")
    with st.form("patient_form"):
        age = st.number_input("Age (years)", min_value=18, max_value=100, value=50)
        if age < 40 or age > 79:
            st.caption("⚠️ The Pooled Cohort Equations are validated for ages 40-79; results outside this range are unreliable.")
        sex = st.selectbox("Sex", ["Male", "Female"])
        race = st.selectbox(
            "Race",
            ["White or Other", "Black or African American"],
            help="The Pooled Cohort Equations were derived and validated for non-Hispanic White and "
                 "African American adults. 'White or Other' uses the White coefficients as the "
                 "guideline-recommended (but imprecise) approximation for other groups.",
        )
        chol = st.number_input("Total Cholesterol (mg/dL)", min_value=100, max_value=400, value=200)
        hdl = st.number_input("HDL Cholesterol (mg/dL)", min_value=20, max_value=100, value=50)
        sbp = st.number_input("Systolic BP (mmHg)", min_value=90, max_value=250, value=120)
        smoker = st.checkbox("Smoker")
        diabetes = st.checkbox("Diabetes")
        bp_meds = st.checkbox("On BP Medications")

        submit = st.form_submit_button("Generate Recommendation")

if submit:
    patient = PatientProfile(
        age=age,
        sex=sex.lower(),
        race="black" if race.startswith("Black") else "white",
        total_cholesterol=chol,
        hdl_cholesterol=hdl,
        systolic_bp=sbp,
        smoker=smoker,
        diabetes=diabetes,
        bp_meds=bp_meds,
    )

    st.write("### Patient Profile Submitted")
    st.json(patient.model_dump())

    with st.spinner("Agent is reasoning..."):
        try:
            result = graph.invoke({"patient": patient, "revision_count": 0})
            risk = result["risk"]
            plan = result["plan"]
            citations = result.get("citations", [])
            critique = result.get("critique")
            revision_count = result.get("revision_count", 0)

            st.success("Recommendation Generated!")
            st.markdown("### Final Care Plan")

            risk_col, meta_col = st.columns([1, 2])
            with risk_col:
                st.metric(
                    "10-Year ASCVD Risk",
                    f"{risk.risk_percentage}%",
                    delta=risk.risk_tier,
                    delta_color="off",
                )
            with meta_col:
                st.caption(f"Method: {risk.method}")
                if risk.out_of_validated_age_range:
                    st.caption("⚠️ Patient age falls outside the equation's validated 40-79 range.")
                if risk.race_approximated_as_white:
                    st.caption("⚠️ Race approximated using White coefficients (guideline-recommended default).")
                if critique is not None:
                    status = "passed" if critique.passes else f"did not fully pass after {revision_count} revision(s) — showing best draft"
                    st.caption(f"Self-critique {status}.")

            sections = [
                ("🩺 Screening", plan.screening),
                ("🥗 Lifestyle", plan.lifestyle),
                ("💊 Pharmacological", plan.pharmacological),
                ("📅 Follow-up", plan.follow_up),
            ]
            cols = st.columns(2)
            for i, (title, items) in enumerate(sections):
                with cols[i % 2]:
                    st.subheader(title)
                    if items:
                        for item in items:
                            st.markdown(f"- {item}")
                    else:
                        st.markdown("_None indicated._")

            if citations:
                with st.expander(f"Guideline sources ({len(citations)})"):
                    for c in citations:
                        st.markdown(f"- {c.source} (page {c.page})")

        except Exception as e:
            st.error(f"An error occurred during agent execution: {str(e)}")
